// <auto-generated />
namespace CreativeFactory.DAL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TagIdColumnMisprintFixed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TagIdColumnMisprintFixed));
        
        string IMigrationMetadata.Id
        {
            get { return "201311211145051_TagIdColumnMisprintFixed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
